blog/urls.py
from django.urls import path, re_path
from . import views

''' app_name='blog', 告诉 Django 这个 urls.py 模块是属于 blog 应用的, 这种技术叫做 视图函数命名空间。
name 属性给这些视图函数取了个别名,
'''
app_name = 'blog'


urlpatterns = [
    # re_path('^$', views.index, name='index'),
    re_path('^$', views.IndexView.as_view(), name='index'),
    # re_path('.*?index.html', views.index,),
    # path('^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    path('post/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    # path('category/<int:pk>/', views.category, name='category'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    re_path('^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
# from blog import views




''' 导入include 函数, 用这个函数把 blog 应用下的 urls.py 文件包含了进来。
Django 会把path参数字符串和后面 include 的 urls.py 文件中的 URL 拼接。
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

comments/urls.py
from django.urls import path, re_path
from . import views

app_name = 'comments'

urlpatterns = [
	path('comment/post/<int:post_pk>', views.post_comment, name='post_comment'),
]

blog/models.py
#coding:utf-8
from django.db import models

# coding:utf-8
# Create your models here.
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


# 分类
@python_2_unicode_compatible
class Category(models.Model):
	# name字段, 储存分类名称
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name


# 标签
@python_2_unicode_compatible
class Tag(models.Model):
	# name字段, 储存标签名称
	name = models.CharField(max_length=100)
	def __str__(self):
		return self.name


# 文章
@python_2_unicode_compatible
class Post(models.Model):
	# 文章标题, 正文
	title = models.CharField(max_length=70)
	body = models.TextField()

	# 创建时间, 修改时间
	created_time = models.DateTimeField()
	modified_time = models.DateTimeField()

	# 摘要 (默认情况下 CharField 要求我们必须存入数据,否则就会报错; CharField 的 blank=True 参数值后就可以允许空值了)
	excerpt = models.CharField(max_length=200, blank=True)

	# 分类,标签 (ForeignKey，即一对多的关联; ManyToManyField，表明这是多对多的关联)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	tags = models.ManyToManyField(Tag, blank=True)

	# 文章作者 (从 django.contrib.auth.models 导入的, Django内置的应用,专门用于处理网站用户的注册、登录等流程的用户模型)
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	# views字段 记录阅读量
	views = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.title

	''' reverse函数, 第一个参数 'blog:detail', 表 blog 应用下的 name=detail 的视图函数。
	于是 reverse 函数会去解析 detail视图函数对应的 URL,  detail 对应的规则 'post/<int:pk>/'。
	如果 Post 的 id是 666, 那么 get_absolute_url 函数返回的就是 /post/666/, 这样 Post 自己就生成了自己的 URL。
	'''
	def get_absolute_url(self):
		return reverse('blog:detail', kwargs = {'pk':self.pk})


	def save(self, *args, **kwargs):
		if not self.excerpt:
			md = markdown.Markdown(extensions=[
				'markdown.extensions.extra',
				'markdown.extensions.codehilite',
				])
			self.excerpt = strip_tags(md.convert(self.body)[:54])
			super(Post, self).save(*args, **kwargs)

	def increase_views(self):
		self.views += 1
		self.save(update_fields=['views'])

	# Meta 类 的 ordering 属性, 指定默认排序方式
	class Meta:
		ordering = ['-created_time', 'title']

comments/models.py
from django.db import models

# Create your models here.

from django.utils.six import python_2_unicode_compatible

@python_2_unicode_compatible
class Comment(models.Model):
	# 名字
	name = models.CharField(max_length=100)
	# 邮箱
	email = models.EmailField(max_length=255)
	# 个人网站
	url = models.URLField(blank=True)
	# 评论内容
	text = models.TextField()
	# 评论时间
	created_time = models.DateTimeField(auto_now_add=True)


	post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

	def __str__(self):
		return self.text[:20]

blog/views.py
#coding:utf-8
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from .models import Post, Category
import markdown

from django.views.generic import ListView
from django.db.models import Q
from comments.forms import CommentForm


class IndexView(ListView):
	model = Post
	template_name = "blog/index.html"
	context_object_name = 'post_list'
	paginate_by = 2

	def get_context_date(self, **kwargs):
		# 首先获得父类生成的传递给模板的字典。
		context = super().get_context_date(**kwargs)
		# 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量

		paginator = context.get('paginator')
		page = context.get('page_obj')
		is_paginated = context.get('is_paginated')
		# 调用 pagination_data 方法获得显示分页导航条需要的数据
		pagination_data = self.pagination_data(paginator, page, is_paginated)
		# 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典
		context.update(pagination_data)

		return context

	def pagination_data(self, paginator, page, is_paginated):
		# 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
		if not is_paginated:
			return {}
		left = []

		right = []

		left_has_more = False
		right_has_more = False

		first = False
		last = False

		page_number = page.number

		total_pages = paginator.num_pages

		page_range = paginator.page_range

		if page_number == 1:
			right = page_range[page_number: page_number+2]

			if right[-1] < total_pages -1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True

		elif page_number == total_pages:
			left = page_range[(page_number - 3) if (page_number -3) > 0 else 0: page_number -1]

			if left[0] >2:
				left_has_more = True
			if left[0] >1:
				first = True
		else:
			left = page_range[(page_number -3) if (page_number -3) > 0 else 0: page_number -1]
			right = page_range[page_number: page_number +2]

			if right[-1] < total_pages -1:
				right_has_more = True
			if right[-1] < total_pages:
				last = True
			if left[0] > 2:
				left_has_more = True
			if left[0] >1:
				first = True


		data = {
		'left':left,
		'right':right,
		'left_has_more':left_has_more,
		'right_has_more':right_has_more,
		'first':first,
		'last':last,
		}
		return data

def index(request):
	post_list = Post.objects.all()
	return render(request, 'blog/index.html', context={'post_list':post})

# def index(request):
# 	post_list = Post.objects.all().order_by('-created_time')
# 	context = {
# 	'post_list': post_list
# 	}
# 	return render(request, 'blog/index.html', context)


''' # detail 视图函数, 根据我们从 URL 捕获的文章 id。
get_object_or_404 方法:  当传入的 pk 对应的 Post 在数据库存在时，就返回对应的 post，
如果不存在，就给用户返回一个 404 错误。
'''
def detail(request, pk):
	post = get_object_or_404(Post, pk=pk)

	# 阅读量 +1
	post.increase_views()

	# 将 Markdown 格式的文本渲染成 HTML 文本。
	# 参数 extensions, 是对 Markdown 语法的拓展(extra、codehilite: 语法高亮拓展、toc: 则允许我们自动生成目录)
	post.body = markdown.markdown(post.body,
		extensions =[
		'markdown.extensions.extra',
		'markdown.extensions.codehilite',
		'markdown.extensions.toc',
		])

	form = CommentForm()
	comment_list = post.comment_set.all()

	context = {	'post': post,
				'form': form,
				'comment_list': comment_list,
				}
	return render(request, 'blog/detail.html', context=context)



# 归档视图
def archives(request, year, month):
	post_list = Post.objects.filter(
		created_time__year = year,
		created_time__month = month
		).order_by('-created_time')
	return render(request, 'blog/index.html', context={'post_list':post_list})

# 分类视图
# def category(request, pk):
# 	cate = get_object_or_404(Category, pk=pk)
# 	post_list = Post.objects.filter(category=cate).order_by('-created_time')
# 	return render(request, 'blog/index.html', context={'post_list':post_list})

class CategoryView(IndexView):
	def get_queryset(self):
		cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
		return super(CategoryView, self).get_queryset().filter(category=cate)

class TagView(ListView):
	model = Post
	template_name = "blog/index.html"
	context_object_name = "post_list"

	def get_queryset(self):
		tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))

		return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
	q = request.GET.get('q')
	error_msg = ''

	if not q:
		error_msg = "请输入关键词"
		return render(request, 'blog/index.html', {'error_msg':error_msg})

	post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
	return render(request, 'blog/index.html', context={'post_list': post_list})

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>

            <div class="entry-meta">
                <span class="post-category">
                	<a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#">
                	<time class="entry-date" datetime="#">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link">
                	<a href="#">{{ post.comment_set.count}} 评论</a></span>
                <span class="views-count"><a href="{{post.get_absolute_url}}">{{post.views}} 阅读</a></span>
            </div>
        </header>

        <div class="entry-content clearfix">
        {{ post.body|safe }}
        <!--  Django 出于安全方面的考虑, 任何的 HTML 代码在 Django 的模板中都会被转义。
        为了解除转义，只需在模板标签使用 safe 过滤器即可。

        safe 是 Django 模板系统中的过滤器（Filter），可以简单地把它看成是一种函数，其作用是作用于模板变量，将模板变量的值变为经过滤器处理过后的值。
         -->
        </div>
    </article>

    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-4">
          <label for="{{ form.name.id_for_label }}">昵称：</label>
          {{ form.name }}
          {{ form.name.errors }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.email.id_for_label }}">邮箱：</label>
          {{ form.email }}
          {{ form.email.errors }}
        </div>
        <div class="col-md-4">
          <label for="{{ form.url.id_for_label }}">URL：</label>
          {{ form.url }}
          {{ form.url.errors }}
        </div>
        <div class="col-md-12">
          <label for="{{ form.text.id_for_label }}">评论：</label>
          {{ form.text }}
          {{ form.text.errors }}
          <button type="submit" class="comment-btn">发表</button>
        </div>
      </div>    <!-- row -->
    </form>

    <ul class="comment-list list-unstyled">
      {% for comment in comment_list %}
      <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date">{{ comment.created_time }}</time>
        <div class="text">
          {{ comment.text }}
        </div>
      </li>
      {% empty %}
      暂无评论
      {% endfor %}
    </ul>

{% endblock main %}

templates/blog/index.html
{% extends 'base.html' %}

<!-- 文章列表页面主体 -->
{% block main %}

    <!-- 文章列表 -->
    {% for post in post_list %}
        <!--   post_list: 是一个 QuerySet（类似于一个列表的数据结构）
        pk (primary key):  即 post 对应于数据库中记录的 id 值，该属性尽管我们没有显示定义，但是 Django 会自动为我们添加.
         -->
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>

                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                    <span class="post-author"><a href="#">{{post.author}}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count}} 评论</a></span>
                    <span class="views-count"><a href="{{post.get_absolute_url}}">{{post.views}} 阅读</a></span>
                </div>
            </header>

            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>

                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post"> 暂时还没有发布文章</div>
    {% endfor %}


    <!-- 分页 -->
    {% if is_paginated %}
    <div class="pagination-simlie">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
            <span class="current">第 {{ page_obj.number }} 页/ 共 {{ paginator.num_pages }}页</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
    </div>
    {% endif %}

{% endblock main %}