blog/urls.py
from django.urls import path, re_path
from . import views

''' app_name='blog', 告诉 Django 这个 urls.py 模块是属于 blog 应用的, 这种技术叫做 视图函数命名空间。
name 属性给这些视图函数取了个别名,
'''
app_name = 'blog'


urlpatterns = [
    # re_path('^$', views.index, name='index'),
    re_path('^$', views.IndexView.as_view(), name='index'),
    # re_path('.*?index.html', views.index,),
    # path('^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    path('post/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    # path('category/<int:pk>/', views.category, name='category'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tag/<int:pk>/', views.TagView.as_view(), name='tag'),
    re_path('^search/$', views.search, name='search'),
]

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
# from blog import views




''' 导入include 函数, 用这个函数把 blog 应用下的 urls.py 文件包含了进来。
Django 会把path参数字符串和后面 include 的 urls.py 文件中的 URL 拼接。
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

templates/base.html
{% load staticfiles %}
{% load blog_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>Green_博客</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}">Green</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <!-- 文章列表页面 -->
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>


            <!-- 侧面栏列表 -->
            <aside class="col-md-4">
                <!-- 最新文章 -->
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <!-- 归档 -->
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                    {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年{{ date.month }} 月</a>
                        </li>
                    {% empty %}
                    暂无归档
                    {% endfor %}
                    </ul>
                </div>
                <!-- 分类 -->
                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                    {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{category.name}}
                            <span class="post-count">({{category.num_posts}})</span></a>
                        </li>
                    {% empty %}
                    暂无归档
                    {% endfor %}
                    </ul>
                </div>
                <!-- 标签云 -->
                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    {% get_tags as tag_list %}
                    <ul>
                    {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk}">{{tag.name}}
                        </li>
                    {% empty %}
                    暂无标签
                    {% endfor %}
                    </ul>
                </div>
            </aside>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">Green</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>